baseURL: "https://ryanbagley.com"
title: Ryan Bagley
paginate: 5
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
canonifyURLs: true
languageCode: en-us
metaDataFormat: yaml
pygmentsUseClasses: false
summarylength: 40

minify:
    disableXML: true
    minifyOutput: false

params:
    font: 'Source Serif Pro'
    env: production # to enable google analytics, opengraph, twitter-cards and schema.
    title: Ryan Bagley
    description: "ExampleSite description"
    keywords: [Blog, Portfolio, PaperMod]
    # author: Ryan Bagley
    # author: ["Me", "You"] # multiple authors
    images: ["<link or path of image for opengraph, twitter-cards>"]
    DateFormat: "January 2, 2006"
    defaultTheme: light
    disableThemeToggle: true

    ShowReadingTime: true
    ShowShareButtons: false
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: false
    disableSpecial1stPost: false
    disableScrollToTop: true
    comments: false
    hidemeta: false
    hideSummary: false
    showtoc: false
    tocopen: false

    assets:
        # disableHLJS: true # to disable highlight.js
        # disableFingerprinting: true
        favicon: "<link / abs url>"
        favicon16x16: "<link / abs url>"
        favicon32x32: "<link / abs url>"
        apple_touch_icon: "<link / abs url>"
        safari_pinned_tab: "<link / abs url>"

    label:
        text: "Ryan Bagley"
        #icon: /apple-touch-icon.png
        #iconHeight: 35

    # profile-mode
    profileMode:
        enabled: false # needs to be explicitly set
        title: ExampleSite
        subtitle: "This is subtitle"
        imageUrl: "<img location>"
        imageWidth: 120
        imageHeight: 120
        imageTitle: my image
        buttons:
            - name: Posts
              url: posts
            - name: Tags
              url: tags

    # home-info mode
    homeInfoParams:
        Title: ""
        Content: "# Hello. 
        
I'm Ryan Bagley, a network engineer 💻 and outdoor adventurer 🏃‍♂️ living in the American West. I enjoy sharing these adventures so that people other than my dogs 🐕‍🦺 can see the beauty of this peculiar geographic region. I also write about topics related to my hobbies and technical interests. You might see a few networking articles sneak in but I will try to mostly keep it easy like Sunday morning. 

If you enjoy thoughtful articles 📚 and some neat pictures from a guy running around in the wilderness 🏕️ then check out an article in my archive or add my RSS feed to your preferred reader."

    socialIcons:
        - name: instagram
          url: "https://www.instagram.com/tcp.rst/"
        - name: telegram
          url: "https://t.me/ryanbagley"
        - name: email
          url: "mailto:ryan@bagley.io"

    analytics:
        google:
            SiteVerificationTag: "XYZabc"
        bing:
            SiteVerificationTag: "XYZabc"
        yandex:
            SiteVerificationTag: "XYZabc"

    cover:
        hidden: true # hide everywhere but not in structured data
        hiddenInList: true # hide on list pages and home
        hiddenInSingle: true # hide on single page

    # for search
    # https://fusejs.io/api/options.html
    fuseOpts:
        isCaseSensitive: false
        shouldSort: true
        location: 0
        distance: 1000
        threshold: 0.4
        minMatchCharLength: 0
        keys: ["title", "permalink", "summary", "content"]
menu:
    main:
        - identifier: archive
          name: Archive
          url: /archives/
          weight: 10
        - identifier: about
          name: About
          url: /about/
          weight: 20
